### PR TITLE
Styling and UI changes

### PR DESCRIPTION
**Pull request by m1ga**
Saw your post on Twitter and would love to add some style and UI changes!

How about something in this direction:
Screenshot 2021-10-01 at 12-05-31 OpenBenches

* excluded the menu to add it to the header and footer
* header is like this on all subpages now (easier navigation)
* moved the map to full width (why not use the space)
* inline search field + button
* move "add bench" to the header to its visible everywhere

_Attention_
I've currently only added the style file since I've made some changes to the PHP files in order to make it work on my machine. I have to clean those up before pushing them.
Just wanted to get your opinion on the layout first!

### CODE REVIEW

**Comment by edent** [comment]
This is great!
Love the clear header and the wider map.

I'd rather keep GitHub & Twitter etc to just be in the footer. I don't think any links need to be in the header.
I *think* the search button looks better under the search field - but happy to give it a go.

Carry on making changes - I'll probably push it live this weekend.

**Comment by m1ga** [comment]
Thanks for the quick feedback! I'll continue to work on it and do some more tweaks!


Screenshot 2021-10-01 at 12-36-16 OpenBenches

* twitter/github items to the bottom and as an icon
* removed + from footer `add bench` (looks better)

The reason for the search button change: the other two buttons can used without the input field; only the `search` button is connected so I've wanted to make a visual connection too.

**Comment by m1ga** [comment]
Search page:

Screenshot 2021-10-01 at 13-35-05 OpenBenches

* search field to the top, makes pager buttons stick out more
* moved all search variantes into `searchForm`, so they are consistent on all pages with `searchForm`
* max text length of 300 charactes and then add `...`. Most people will go to the details page anyway, so why display all in the results
* item text won't go under image now, cleaner look.
* number inside `li`

**Comment by m1ga** [comment]
Feel free to check and review it now!

If you'll want any changes I'm happy to merge them in.

**Pull request merged**
